"""core schema

Revision ID: 605c28cd588a
Revises: 0001
Create Date: 2026-08-11 00:56:11.829194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('document', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('timezone', sa.String(length=64), server_default='America/Sao_Paulo', nullable=False),
    sa.Column('status', postgresql.ENUM('trial', 'active', 'suspended', 'cancelled', name='organization_status', create_type=False), server_default='trial', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('slug', name=op.f('uq_organizations_slug'))
    )
    op.create_table('permissions',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('module', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_permissions'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=120), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', postgresql.ENUM('create', 'update', 'delete', name='audit_action', create_type=False), nullable=False),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_audit_logs_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_table('branches',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('address_line', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip_code', sa.String(length=16), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_branches_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branches')),
    sa.UniqueConstraint('organization_id', 'slug', name=op.f('uq_branches_organization_id_slug'))
    )
    op.create_table('clients',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('whatsapp', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_clients_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clients'))
    )
    op.create_index('ix_clients_org_name', 'clients', ['organization_id', 'name'], unique=False)
    op.create_index('ix_clients_org_phone', 'clients', ['organization_id', 'phone'], unique=False)
    op.create_table('recurrences',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('frequency', postgresql.ENUM('daily', 'weekly', 'biweekly', 'monthly', 'custom', name='recurrence_frequency', create_type=False), nullable=False),
    sa.Column('interval', sa.Integer(), server_default='1', nullable=False),
    sa.Column('days_of_week', sa.ARRAY(sa.SmallInteger()), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('occurrences_count', sa.Integer(), nullable=True),
    sa.Column('status', postgresql.ENUM('active', 'paused', 'cancelled', name='recurrence_status', create_type=False), server_default='active', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_recurrences_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recurrences'))
    )
    op.create_table('roles',
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_roles_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_index('uq_roles_org_name', 'roles', ['organization_id', 'name'], unique=True, postgresql_where='organization_id IS NOT NULL')
    op.create_index('uq_roles_system_name', 'roles', ['name'], unique=True, postgresql_where='organization_id IS NULL')
    op.create_table('services',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('default_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('default_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_services_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services'))
    )
    op.create_table('tags',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_tags_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('organization_id', 'name', name=op.f('uq_tags_organization_id_name'))
    )
    op.create_table('appointments',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('scheduled', 'confirmed', 'waiting', 'in_progress', 'finished', 'cancelled', 'no_show', name='appointment_status', create_type=False), server_default='scheduled', nullable=False),
    sa.Column('source', postgresql.ENUM('internal', 'public_booking', name='appointment_source', create_type=False), server_default='internal', nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('starts_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('ends_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('recurrence_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_appointments_branch_id_branches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_appointments_client_id_clients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_appointments_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_appointments_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recurrence_id'], ['recurrences.id'], name=op.f('fk_appointments_recurrence_id_recurrences'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_appointments_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments'))
    )
    op.create_index(op.f('ix_appointments_client_id'), 'appointments', ['client_id'], unique=False)
    op.create_index('ix_appointments_org_branch_starts', 'appointments', ['organization_id', 'branch_id', 'starts_at'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_table('organization_memberships',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('status', postgresql.ENUM('invited', 'active', 'suspended', 'removed', name='membership_status', create_type=False), server_default='invited', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_organization_memberships_branch_id_branches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_memberships_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_organization_memberships_role_id_roles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_organization_memberships_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_memberships')),
    sa.UniqueConstraint('user_id', 'organization_id', name=op.f('uq_organization_memberships_user_id_organization_id'))
    )
    op.create_table('professionals',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('professional_email', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('agenda_color', sa.String(length=7), server_default='#8B5CF6', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_professionals_branch_id_branches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_professionals_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_professionals_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_professionals'))
    )
    op.create_index('uq_professionals_org_user', 'professionals', ['organization_id', 'user_id'], unique=True, postgresql_where='user_id IS NOT NULL')
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_key', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['permission_key'], ['permissions.key'], name=op.f('fk_role_permissions_permission_key_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_key', name=op.f('pk_role_permissions'))
    )
    op.create_table('appointment_items',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('start_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', postgresql.ENUM('scheduled', 'confirmed', 'waiting', 'in_progress', 'finished', 'cancelled', 'no_show', name='appointment_status', create_type=False), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_at > start_at', name=op.f('ck_appointment_items_end_after_start')),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_appointment_items_appointment_id_appointments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_appointment_items_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], name=op.f('fk_appointment_items_professional_id_professionals'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_appointment_items_service_id_services'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointment_items'))
    )
    op.create_index('ix_appointment_items_professional_range', 'appointment_items', ['professional_id', 'start_at', 'end_at'], unique=False)
    op.create_table('appointment_tags',
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_appointment_tags_appointment_id_appointments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_appointment_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('appointment_id', 'tag_id', name=op.f('pk_appointment_tags'))
    )
    op.create_table('membership_permission_overrides',
    sa.Column('membership_id', sa.UUID(), nullable=False),
    sa.Column('permission_key', sa.String(length=120), nullable=False),
    sa.Column('effect', postgresql.ENUM('grant', 'deny', name='permission_effect', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['organization_memberships.id'], name=op.f('fk_membership_permission_overrides_membership_id_organization_memberships'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_key'], ['permissions.key'], name=op.f('fk_membership_permission_overrides_permission_key_permissions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('membership_id', 'permission_key', name=op.f('pk_membership_permission_overrides'))
    )
    op.create_table('professional_services',
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('duration_override_minutes', sa.Integer(), nullable=True),
    sa.Column('price_override', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('commission_type', postgresql.ENUM('percentage', 'fixed', name='commission_type', create_type=False), nullable=True),
    sa.Column('commission_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], name=op.f('fk_professional_services_professional_id_professionals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_professional_services_service_id_services'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_professional_services')),
    sa.UniqueConstraint('professional_id', 'service_id', name=op.f('uq_professional_services_professional_id_service_id'))
    )
    op.create_table('schedule_blocks',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('scope', postgresql.ENUM('professional', 'branch', 'organization', name='schedule_block_scope', create_type=False), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('block_type', postgresql.ENUM('lunch', 'meeting', 'day_off', 'vacation', 'unavailable', 'maintenance', 'other', name='schedule_block_type', create_type=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('start_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('recurrence_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(scope = 'professional' AND professional_id IS NOT NULL) OR (scope = 'branch' AND branch_id IS NOT NULL AND professional_id IS NULL) OR (scope = 'organization' AND branch_id IS NULL AND professional_id IS NULL)", name=op.f('ck_schedule_blocks_scope_consistency')),
    sa.CheckConstraint('end_at > start_at', name=op.f('ck_schedule_blocks_end_after_start')),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_schedule_blocks_branch_id_branches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_schedule_blocks_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], name=op.f('fk_schedule_blocks_professional_id_professionals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recurrence_id'], ['recurrences.id'], name=op.f('fk_schedule_blocks_recurrence_id_recurrences'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_blocks'))
    )
    op.create_index('ix_schedule_blocks_branch_range', 'schedule_blocks', ['branch_id', 'start_at', 'end_at'], unique=False)
    op.create_index('ix_schedule_blocks_org_range', 'schedule_blocks', ['organization_id', 'start_at', 'end_at'], unique=False)
    op.create_index('ix_schedule_blocks_professional_range', 'schedule_blocks', ['professional_id', 'start_at', 'end_at'], unique=False)
    op.create_table('working_hours',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('professional_id', sa.UUID(), nullable=False),
    sa.Column('weekday', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('start_time < end_time', name=op.f('ck_working_hours_start_before_end')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_working_hours_organization_id_organizations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], name=op.f('fk_working_hours_professional_id_professionals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_working_hours'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('working_hours')
    op.drop_index('ix_schedule_blocks_professional_range', table_name='schedule_blocks')
    op.drop_index('ix_schedule_blocks_org_range', table_name='schedule_blocks')
    op.drop_index('ix_schedule_blocks_branch_range', table_name='schedule_blocks')
    op.drop_table('schedule_blocks')
    op.drop_table('professional_services')
    op.drop_table('membership_permission_overrides')
    op.drop_table('appointment_tags')
    op.drop_index('ix_appointment_items_professional_range', table_name='appointment_items')
    op.drop_table('appointment_items')
    op.drop_table('role_permissions')
    op.drop_index('uq_professionals_org_user', table_name='professionals', postgresql_where='user_id IS NOT NULL')
    op.drop_table('professionals')
    op.drop_table('organization_memberships')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index('ix_appointments_org_branch_starts', table_name='appointments')
    op.drop_index(op.f('ix_appointments_client_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_table('tags')
    op.drop_table('services')
    op.drop_index('uq_roles_system_name', table_name='roles', postgresql_where='organization_id IS NULL')
    op.drop_index('uq_roles_org_name', table_name='roles', postgresql_where='organization_id IS NOT NULL')
    op.drop_table('roles')
    op.drop_table('recurrences')
    op.drop_index('ix_clients_org_phone', table_name='clients')
    op.drop_index('ix_clients_org_name', table_name='clients')
    op.drop_table('clients')
    op.drop_table('branches')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('permissions')
    op.drop_table('organizations')
    # ### end Alembic commands ###
